image: debian/stable

packages:
  - python3
  - python3-virtualenv
  - python3-setuptools

sources:
  - https://git.sr.ht/~jmstover/ps3iso

tasks:
  - setup: |
      cd ps3iso
      python3 -m virtualenv -p python3 venv
      source venv/bin/activate
      python -V
      pip install -q -r requirements-dev.txt
  - build: |
      cd ps3iso
      source venv/bin/activate
      make test

